openapi: 3.0.1
info:
  title: Mainflux webhooks service
  description: HTTP API for managing platform webhooks.
  version: 1.0.0

paths:
  /groups/{groupId}/webhooks:
    post:
      summary: Adds new webhooks
      description: |
        Adds new webhooks to the list of webhooks for certain group identified by the provided ID
      tags:
        - webhooks
      parameters:
        - $ref: "#/components/parameters/GroupId"
      requestBody:
        $ref: "#/components/requestBodies/WebhooksCreateReq"
      responses:
        '201':
          $ref: "#/components/responses/WebhooksCreateRes"
        '400':
          description: Failed due to malformed JSON.
        '401':
          description: Missing or invalid access token provided.
        '403':
          description: Failed to perform authorization over the entity
        '415':
          description: Missing or invalid content type.
        '500':
          $ref: "#/components/responses/ServiceError"
    get:
      summary: Retrieves webhooks by group
      description: Retrieves list of webhooks related to a certain group identified by the provided ID.
      tags:
        - webhooks
      parameters:
        - $ref: "#/components/parameters/GroupId"
      responses:
        '200':
          $ref: "#/components/responses/WebhooksListRes"
        '400':
          description: Failed due to malformed query parameters.
        '401':
          description: Missing or invalid access token provided.
        '403':
          description: Failed to perform authorization over the entity
        '422':
          description: Database can't process request.
        '500':
          $ref: "#/components/responses/ServiceError"
    patch:
      summary: Removes webhooks
      description: Removes webhooks with provided identifiers
      tags:
        - webhooks
      parameters:
        - $ref: "#/components/parameters/GroupId"
      requestBody:
        $ref: "#/components/requestBodies/WebhookRemoveReq"
      responses:
        '204':
          description: Webhook removed.
        '400':
          description: Failed due to malformed JSON.
        '401':
          description: Missing or invalid access token provided.
        '500':
          $ref: "#/components/responses/ServiceError"
  /webhooks/{webhookId}:
    get:
      summary: Retrieves webhook info
      tags:
        - webhooks
      parameters:
        - $ref: "#/components/parameters/WebhookId"
      responses:
        '200':
          $ref: "#/components/responses/WebhookRes"
        '401':
          description: Missing or invalid access token provided.
        '404':
          description: Webhook does not exist.
        '422':
          description: Database can't process request.
        '500':
          $ref: "#/components/responses/ServiceError"
    put:
      summary: Updates webhook info
      description: |
        Update is performed by replacing the current resource data with values
        provided in a request payload. Note that the webhook's ID cannot be changed.
      tags:
        - webhooks
      parameters:
        - $ref: "#/components/parameters/WebhookId"
      requestBody:
        $ref: "#/components/requestBodies/WebhookUpdateReq"
      responses:
        '200':
          description: Webhook updated.
        '400':
          description: Failed due to malformed JSON.
        '401':
          description: Missing or invalid access token provided.
        '404':
          description: Webhook does not exist.
        '415':
          description: Missing or invalid content type.
        '500':
          $ref: "#/components/responses/ServiceError"

components:
  schemas:
    WebhookReqSchema:
      type: object
      properties:
        name:
          type: string
          description: Name of webhook.
        url:
          type: string
          description: The url to which the message will be forwarded.
        headers:
          type: object
          description: HTTP headers specified for the webhook.
          additionalProperties:
            type: string
      required:
        - name
        - url
    WebhookResSchema:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique webhook identifier generated by the service.
        group_id:
          type: string
          format: uuid
          description: The group identifier refers to the group for which the webhook was created.
        name:
          type: string
          description: Name of webhook.
          example: "Test Webhook"
        url:
          type: string
          description: The url to which the message will be forwarded.
          example: "https://test.webhook.com"
        headers:
          type: object
          description: HTTP Headers specified for the webhook.
          additionalProperties:
            type: string
          example:
            Content-Type: "application/json"
      required:
        - id
        - group_id
        - name
        - url
        - headers

  parameters:
    WebhookId:
      name: webhookId
      description: Unique webhook identifier.
      in: path
      schema:
        type: string
        format: uuid
      required: true
    GroupId:
      name: groupId
      description: Group identifier refers to the group for which the webhook is being created.
      in: path
      schema:
        type: string
        format: uuid
      required: true


  requestBodies:
    WebhooksCreateReq:
      description: JSON-formatted document describing the new webhooks.
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              webhooks:
                type: array
                items:
                  $ref: "#/components/schemas/WebhookReqSchema"
    WebhookUpdateReq:
      description: JSON-formatted document describing the updated webhook info.
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of webhook.
              url:
                type: string
                description: The url to which the message will be forwarded.
              headers:
                type: object
                description: HTTP headers specified for the webhook.
                additionalProperties:
                  type: string
    WebhookRemoveReq:
      description: JSON-formatted document describing the identifiers of webhooks for deleting.
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              webhook_ids:
                type: array
                items:
                  type: string
                  format: uuid

  responses:
    WebhooksCreateRes:
      description: Webhooks created.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/WebhookResSchema"
    WebhookRes:
      description: Data retrieved.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WebhookResSchema"
    WebhooksListRes:
      description: Webhooks retrieved.
      content:
        application/json:
          schema:
            type: object
            properties:
              webhooks:
                type: array
                items:
                  $ref: "#/components/schemas/WebhookResSchema"
            required:
              - webhooks
    ServiceError:
      description: Unexpected server-side error occurred.
      content:
        application/json:
          schema:
            type: string
            format: byte

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        * Users access: "Authorization: Bearer <user_token>"

security:
  - bearerAuth: [ ]
