openapi: 3.0.1
info:
  title: Mainflux http adapter
  description: HTTP API for sending messages.
  version: "1.0.0"
paths:
  /messages:
    post:
      summary: Sends message
      description: |
        Sends message. Messages can be sent as
        JSON formatted SenML or as blob.
      tags:
        - messages
      requestBody:
        $ref: "#/components/requestBodies/MessageReq"
      responses:
        "202":
          description: Message is accepted for processing.
        "400":
          description: Message discarded due to its malformed content.
        "401":
          description: Missing or invalid access token provided.
        "415":
          description: Message discarded due to invalid or missing content type.
        '500':
          $ref: "#/components/responses/ServiceError"

  /messages/{subtopic}:
    post:
      summary: Sends message to a subtopic
      description: |
        Sends message to a specific subtopic (supports nested paths).
        Messages can be sent as JSON formatted SenML or as blob.
      tags:
        - messages
      parameters:
        - name: subtopic
          in: path
          required: true
          schema:
            type: string
          description: "Subtopic path (e.g., 'alerts/weather' or 'updates/tech/ai')"
      requestBody:
        $ref: "#/components/requestBodies/MessageReq"
      responses:
        "202":
          description: Message is accepted for processing.
        "400":
          description: Message discarded due to its malformed content.
        "401":
          description: Missing or invalid access token provided.
        "415":
          description: Message discarded due to invalid or missing content type.
        '500':
          $ref: "#/components/responses/ServiceError"

  /things/{thingId}/commands:
    post:
      summary: Send a command to a thing
      description: |
        Sends a command to a specific thing.
        Commands represent instructions for device behavior
        (e.g. reboot, configuration update).
      tags:
        - commands
      parameters:
        - $ref: "#/components/parameters/ThingId"
      requestBody:
        $ref: "#/components/requestBodies/CommandReq"
      responses:
        "202":
          description: Command accepted for processing.
        "400":
          description: Invalid command payload.
        "401":
          description: Missing or invalid access token provided.
        "500":
          $ref: "#/components/responses/ServiceError"

  /things/{thingId}/commands/{subtopic}:
    post:
      summary: Send a command to a thing subtopic
      description: |
        Sends a command to a specific subtopic of a thing.
        Subtopics can be used to route commands to
        specific device modules or capabilities.
        Example subtopics:
          - "firmware"
          - "config/network"
          - "actuators/relay1"
      tags:
        - commands
      parameters:
        - $ref: "#/components/parameters/ThingId"
        - name: subtopic
          in: path
          required: true
          schema:
            type: string
          description: Subtopic path for command routing.
      requestBody:
        $ref: "#/components/requestBodies/CommandReq"
      responses:
        "202":
          description: Command accepted for processing.
        "400":
          description: Invalid command payload.
        "401":
          description: Missing or invalid access token provided.
        "500":
          $ref: "#/components/responses/ServiceError"

  /groups/{groupId}/commands:
    post:
      summary: Send a command to a group
      description: |
        Sends a command to all things within a group.
        Commands represent instructions for device behavior
        (e.g. reboot, configuration update).
        Each thing in the group will receive the same command.
      tags:
        - commands
      parameters:
        - $ref: "#/components/parameters/GroupId"
      requestBody:
        $ref: "#/components/requestBodies/CommandReq"
      responses:
        "202":
          description: Command accepted for processing.
        "400":
          description: Invalid command payload.
        "401":
          description: Missing or invalid access token provided.
        "500":
          $ref: "#/components/responses/ServiceError"

  /groups/{groupId}/commands/{subtopic}:
    post:
      summary: Send a command to a group subtopic
      description: |
        Sends a command to a specific subtopic of all things
        within a group.
        Subtopics can be used to route commands to
        specific device modules or capabilities.
        Example subtopics:
          - "firmware"
          - "config/network"
          - "actuators/relay1"
      tags:
        - commands
      parameters:
        - $ref: "#/components/parameters/GroupId"
        - name: subtopic
          in: path
          required: true
          schema:
            type: string
          description: Subtopic path for command routing.
      requestBody:
        $ref: "#/components/requestBodies/CommandReq"
      responses:
        "202":
          description: Command accepted for processing.
        "400":
          description: Invalid command payload.
        "401":
          description: Missing or invalid access token provided.
        "500":
          $ref: "#/components/responses/ServiceError"

  /health:
    get:
      summary: Retrieves service health check info.
      tags:
        - health
      responses:
        '200':
          $ref: "#/components/responses/HealthRes"
        '500':
          $ref: "#/components/responses/ServiceError"

components:
  schemas:
    SenMLRecord:
      type: object
      properties:
        bn:
          type: string
          description: Base Name
        bt:
          type: number
          format: double
          description: Base Time
        bu:
          type: number
          format: double
          description: Base Unit
        bv:
          type: number
          format: double
          description: Base Value
        bs:
          type: number
          format: double
          description: Base Sum
        bver:
          type: number
          format: double
          description: Version
        n:
          type: string
          description: Name
        u:
          type: string
          description: Unit
        v:
          type: number
          format: double
          description: Value
        vs:
          type: string
          description: String Value
        vb:
          type: boolean
          description: Boolean Value
        vd:
          type: string
          description: Data Value
        s:
          type: number
          format: double
          description: Value Sum
        t:
          type: number
          format: double
          description: Time
        ut:
          type: number
          format: double
          description: Update Time
    SenMLArray:
      type: array
      items:
        $ref: "#/components/schemas/SenMLRecord"
    CommandPayload:
      type: object
      required:
        - command
      properties:
        command:
          type: string
          description: |
            Name of the command to be executed by the thing
            (e.g. "reboot", "set_threshold", "start_firmware_update").
        params:
          type: object
          additionalProperties: true
          description: Command-specific parameters.
        metadata:
          type: object
          additionalProperties: true
          description: Optional metadata (request id, timestamps, etc).

  parameters:
    ThingId:
      name: thingId
      description: Unique thing identifier.
      in: path
      schema:
        type: string
        format: uuid
      required: true
    GroupId:
      name: groupId
      description: Unique group identifier.
      in: path
      schema:
        type: string
        format: uuid
      required: true

  requestBodies:
    MessageReq:
      description: |
        Message to be distributed. Since the platform expects messages to be
        properly formatted SenML in order to be post-processed, clients are
        obliged to specify Content-Type header for each published message.
        Note that all messages that aren't SenML will be accepted and published,
        but no post-processing will be applied.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SenMLArray"
    CommandReq:
      description: |
        Command instruction sent to a thing or group.
        Payload usually represents an action
        that the target thing(s) should execute.
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CommandPayload"

  responses:
    ServiceError:
      description: Unexpected server-side error occurred.
      content:
        application/json:
          schema:
            type: string
            format: byte
    HealthRes:
      description: Service Health Check.
      content:
        application/json:
          schema:
            $ref: "./schemas/HealthInfo.yml"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: uuid
      description: |
        * Thing access: "Authorization: Thing <thing_key>"

    basicAuth:
      type: http
      scheme: basic
      description: |
        * Things access: "Authorization: Basic <base64-encoded_credentials>"
    
    externalAuth:
      type: http
      scheme: bearer
      bearerFormat: string
      description: |
        * Thing access: "Authorization: External <external_thing_key>"

security:
  - bearerAuth: []
  - basicAuth: []
  - externalAuth: []
