openapi: 3.0.1
info:
  title: Mainflux ws adapter
  description: WebSocket API for sending messages through communication channels.
  version: "1.0.0"
paths:
  /messages:
    post:
      summary: Sends a message
      description: |
        Sends a message without a subtopic. Messages can be sent as
        JSON-formatted SenML or as binary data.
      tags:
        - messages
      requestBody:
        $ref: "#/components/requestBodies/MessageReq"
      responses:
        "202":
          description: Message is accepted for processing.
        "400":
          description: Message discarded due to malformed content.
        "401":
          description: Missing or invalid access token provided.
        "415":
          description: Invalid or missing content type.
        "500":
          $ref: "#/components/responses/ServiceError"

  /messages/{subtopic}:
    post:
      summary: Sends a message to a subtopic (supports nested paths)
      description: |
        Sends a message to a specific subtopic (e.g., `notifications/urgent`).
        Supports nested subtopics with `/`.
      tags:
        - messages
      parameters:
        - name: subtopic
          in: path
          required: true
          schema:
            type: string
          description: "Subtopic path (e.g., 'alerts/weather' or 'updates/tech/ai')"
      requestBody:
        $ref: "#/components/requestBodies/MessageReq"
      responses:
        "202":
          description: Message is accepted for processing.
        "400":
          description: Message discarded due to malformed content.
        "401":
          description: Missing or invalid access token provided.
        "415":
          description: Invalid or missing content type.
        "500":
          $ref: "#/components/responses/ServiceError"

  /health:
    get:
      summary: Retrieves service health check info.
      tags:
        - health
      responses:
        '200':
          $ref: "#/components/responses/HealthRes"
        '500':
          $ref: "#/components/responses/ServiceError"