# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional SMTP-Notifier-DB and SMTP-Notifier services
# for the Mainflux platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  mainfluxlabs-base-net:
    external: true

volumes:
  mainfluxlabs-smtp-notifier-db-volume:

services:
  smtp-notifier-db:
    image: postgres:13.3-alpine
    container_name: mainfluxlabs-smtp-notifier-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${MF_SMTP_NOTIFIER_DB_USER}
      POSTGRES_PASSWORD: ${MF_SMTP_NOTIFIER_DB_PASS}
      POSTGRES_DB: ${MF_SMTP_NOTIFIER_DB}
    networks:
      - mainfluxlabs-base-net
    volumes:
      - mainfluxlabs-smtp-notifier-db-volume:/var/lib/postgresql/data

  smtp-notifier:
    image: mainfluxlabs/smtp-notifier:${MF_RELEASE_TAG}
    container_name: mainfluxlabs-smtp-notifier
    depends_on:
      - smtp-notifier-db
    restart: on-failure
    environment:
      MF_SMTP_NOTIFIER_LOG_LEVEL: ${MF_SMTP_NOTIFIER_LOG_LEVEL}
      MF_SMTP_NOTIFIER_PORT: ${MF_SMTP_NOTIFIER_PORT}
      MF_BROKER_URL: ${MF_BROKER_URL}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_EMAIL_USERNAME: ${MF_EMAIL_USERNAME}
      MF_EMAIL_PASSWORD: ${MF_EMAIL_PASSWORD}
      MF_EMAIL_HOST: ${MF_EMAIL_HOST}
      MF_EMAIL_PORT: ${MF_EMAIL_PORT}
      MF_EMAIL_FROM_ADDRESS: ${MF_EMAIL_FROM_ADDRESS}
      MF_EMAIL_FROM_NAME: ${MF_EMAIL_FROM_NAME}
      MF_EMAIL_TEMPLATE: ${MF_EMAIL_TEMPLATE}
      MF_SMTP_NOTIFIER_TEMPLATE: ${MF_SMTP_NOTIFIER_TEMPLATE}
      MF_SMTP_NOTIFIER_FROM_ADDR: ${MF_SMTP_NOTIFIER_FROM_ADDR}
      MF_SMTP_NOTIFIER_DB_HOST: smtp-notifier-db
      MF_SMTP_NOTIFIER_DB_PORT: ${MF_SMTP_NOTIFIER_DB_PORT}
      MF_SMTP_NOTIFIER_DB_USER: ${MF_SMTP_NOTIFIER_DB_USER}
      MF_SMTP_NOTIFIER_DB_PASS: ${MF_SMTP_NOTIFIER_DB_PASS}
      MF_SMTP_NOTIFIER_DB: ${MF_SMTP_NOTIFIER_DB}
      MF_SMTP_NOTIFIER_SERVER_CERT: ${MF_SMTP_NOTIFIER_SERVER_CERT}
      MF_SMTP_NOTIFIER_SERVER_KEY: ${MF_SMTP_NOTIFIER_SERVER_KEY}
      MF_THINGS_AUTH_GRPC_URL: ${MF_THINGS_AUTH_GRPC_URL}
      MF_THINGS_AUTH_GRPC_TIMEOUT: ${MF_THINGS_AUTH_GRPC_TIMEOUT}
    ports:
      - ${MF_SMTP_NOTIFIER_PORT}:${MF_SMTP_NOTIFIER_PORT}
    networks:
      - mainfluxlabs-base-net
    volumes:
      - ../../templates/${MF_SMTP_NOTIFIER_TEMPLATE}:/${MF_EMAIL_TEMPLATE}
