// Copyright (c) Mainflux
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package protomfx;

import "google/protobuf/empty.proto";

message Message {
    string publisher    = 1;
    string subtopic     = 2;
    bytes payload       = 3;
    string content_type = 4;
    string protocol     = 5;
    int64 created       = 6; // Unix timestamp in nanoseconds
}

message Command {
    string publisher    = 1;
    string subtopic     = 2;
    bytes payload       = 3;
    string recipient_id = 4;
    string protocol     = 5;
    int64 created       = 6; // Unix timestamp in nanoseconds
}

service ReadersService {
    rpc ListJSONMessages(ListJSONMessagesReq)   returns (ListJSONMessagesRes)  {}
    rpc ListSenMLMessages(ListSenMLMessagesReq) returns (ListSenMLMessagesRes) {}
}

message Alarm {
    string thing_id  = 1;
    string subtopic  = 2;
    string protocol  = 3;
    int64  created   = 4;
    int32  level     = 5;
    string rule_id   = 6;
    bytes  rule_info = 7;
}

message Notification {
    string thing_id  = 1;
    string subtopic  = 2;
    string protocol  = 3;
    bytes  payload   = 4;
    int64  created   = 5;
}

message Webhook {
    string thing_id  = 1;
    bytes  payload   = 2;
    int64  created   = 3;
}

service ThingsService {
    rpc GetPubConfigByKey(ThingKey) returns (PubConfigByKeyRes) {}
    rpc GetConfigByThing(ThingID) returns (ConfigByThingRes){}
    rpc CanUserAccessThing(UserAccessReq) returns (google.protobuf.Empty) {}
    rpc CanUserAccessProfile(UserAccessReq) returns (google.protobuf.Empty) {}
    rpc CanUserAccessGroup(UserAccessReq) returns (google.protobuf.Empty) {}
    rpc CanThingAccessGroup(ThingAccessReq) returns (google.protobuf.Empty) {}
    rpc CanThingCommand(ThingCommandReq) returns (google.protobuf.Empty) {}
    rpc CanThingGroupCommand(ThingGroupCommandReq) returns (google.protobuf.Empty) {}
    rpc Identify(ThingKey) returns (ThingID) {}
    rpc GetGroupIDByThing(ThingID) returns (GroupID) {}
    rpc GetGroupIDByProfile(ProfileID) returns (GroupID) {}
    rpc GetGroupIDsByOrg(OrgAccessReq) returns (GroupIDs) {}
    rpc GetThingIDsByProfile(ProfileID) returns (ThingIDs) {}
    rpc CreateGroupMemberships(CreateGroupMembershipsReq) returns (google.protobuf.Empty) {}
    rpc GetGroup(GetGroupReq) returns (Group) {}
    rpc GetKeyByThingID(ThingID) returns (ThingKey) {}
}

service UsersService {
    rpc GetUsersByIDs(UsersByIDsReq) returns (UsersRes) {}
    rpc GetUsersByEmails(UsersByEmailsReq) returns (UsersRes) {}
}

service AuthService {
    rpc Issue(IssueReq) returns (Token) {}
    rpc Refresh(Token) returns (Token) {}
    rpc RevokeSessions(RevokeSessionsReq) returns (google.protobuf.Empty) {}
    rpc Identify(Token) returns (UserIdentity) {}
    rpc Authorize(AuthorizeReq) returns (google.protobuf.Empty) {}
    rpc GetOwnerIDByOrg(OrgID) returns (OwnerID) {}
    rpc AssignRole(AssignRoleReq) returns (google.protobuf.Empty) {}
    rpc RetrieveRole(RetrieveRoleReq) returns (RetrieveRoleRes) {}
    rpc CreateDormantOrgInvite(CreateDormantOrgInviteReq) returns (google.protobuf.Empty) {}
    rpc ActivateOrgInvite(ActivateOrgInviteReq) returns (google.protobuf.Empty) {}
    rpc GetDormantOrgInviteByPlatformInvite(GetDormantOrgInviteByPlatformInviteReq) returns (OrgInvite) {}
    rpc ViewOrg(ViewOrgReq) returns (Org) {}
}

message ThingKey {
    string value = 1;
    string type  = 2;
}

message PubConfigByKeyRes {
    string publisher_id   = 1;
    Config profile_config = 2;
}

message Config {
    string content_type     = 1;
    Transformer transformer = 2;
    bool write_enabled      = 3;
    bool webhook_enabled    = 4;
    bool rule_enabled       = 5;
}

message ConfigByThingRes{
    Config config = 1;
}

message Transformer {
    repeated string data_filters = 1;
    string data_field            = 2;
    string time_field            = 3;
    string time_format           = 4;
    string time_location         = 5;
}

message ThingID {
    string value = 1;
}

message ThingIDs {
    repeated string ids = 1;
}

message ProfileID {
    string value = 1;
}

message GroupID {
    string value = 1;
}

message GroupIDs {
    repeated string ids = 1;
}

message OrgID {
    string value = 1;
}

message OwnerID {
    string value = 1;
}

// If a token is not carrying any information itself, the type
// field can be used to determine how to validate the token.
// Also, different tokens can be encoded in different ways.
message Token {
    string value = 1;
}

message UserIdentity {
    string id    = 1;
    string email = 2;
}

message IssueReq {
    string id    = 1;
    string email = 2;
    uint32 type  = 3;
}

message RevokeSessionsReq {
    string id = 1;
}

message AuthorizeReq {
    string token   = 1;
    string object  = 2;
    string subject = 3;
    string action  = 4;
}

message UserAccessReq {
    string token  = 1;
    string id     = 2;
    string action = 3;
}

message ThingAccessReq {
    string key = 1;
    string id  = 2;
}

message ThingCommandReq {
    string publisher_id = 1;
    string recipient_id = 2;
}

message ThingGroupCommandReq {
    string publisher_id = 1;
    string group_id     = 2;
}

message User {
    string id     = 1;
    string email  = 2;
    string status = 3;
}

message PageMetadata {
    uint64 total  = 1;
    uint64 offset = 2;
    uint64 limit  = 3;
    string email  = 4;
    string order  = 5;
    string dir    = 6;
}

message UsersByEmailsReq {
    repeated string emails = 1;
}

message UsersByIDsReq {
    repeated string ids        = 1;
    PageMetadata page_metadata = 2;
}

message UsersRes {
    repeated User users        = 1;
    PageMetadata page_metadata = 2;
}

message AssignRoleReq {
    string id   = 1;
    string role = 2;
}

message RetrieveRoleReq {
    string id = 1;
}

message RetrieveRoleRes {
    string role = 1;
}

message OrgAccessReq {
    string org_id = 1;
    string token  = 2;
}

message GroupInvite {
    string group_id = 1;
    string member_role = 2;
}

message CreateDormantOrgInviteReq {
    string token = 1;
    string org_id = 2;
    string invitee_role = 3;
    string platform_invite_id = 4;
    repeated GroupInvite group_invites = 5;
}

message ActivateOrgInviteReq {
    string platform_invite_id = 1;
    string user_id = 2;
    string redirect_path = 3;
}

message GroupMembership {
    string user_id = 1;
    string group_id = 2;
    string role = 3;
}

message CreateGroupMembershipsReq {
    repeated GroupMembership memberships = 1;
}

message GetDormantOrgInviteByPlatformInviteReq {
    string platform_invite_id = 1;
}

message OrgInvite {
    string id = 1;
    string org_id = 2;
    string org_name = 3;
    string invitee_role = 4;
    repeated GroupInvite group_invites = 5;
}

message ViewOrgReq {
    string token = 1;
    string org_id = 2;
}

message Org {
    string id = 1;
    string owner_id = 2;
    string name = 3;
}

message GetGroupReq {
    string group_id = 1;
}

message Group {
    string id = 1;
    string org_id = 2;
    string name = 3;
}

message ListJSONMessagesReq {
    ThingKey        thing_key    = 1;
    uint64          offset       = 2;
    uint64          limit        = 3;
    string          subtopic     = 4;
    string          publisher    = 5;
    string          protocol     = 6;
    int64           from         = 7;
    int64           to           = 8;
    string          filter       = 9;
    string          agg_interval = 10;
    uint64          agg_value    = 11;
    string          agg_type     = 12;
    repeated string agg_fields   = 13;
    string          dir          = 14;
}

message ListJSONMessagesRes {
    uint64           total    = 1;
    repeated Message messages = 2;
}

message ListSenMLMessagesReq {
    ThingKey        thing_key    = 1;
    uint64          offset       = 2;
    uint64          limit        = 3;
    string          subtopic     = 4;
    string          publisher    = 5;
    string          protocol     = 6;
    string          name         = 7;
    double          value        = 8;
    string          comparator   = 9;
    bool            bool_value   = 10;
    string          string_value = 11;
    string          data_value   = 12;
    int64           from         = 13;
    int64           to           = 14;
    string          agg_interval = 15;
    uint64          agg_value    = 16;
    string          agg_type     = 17;
    repeated string agg_fields   = 18;
    string          dir          = 19;
}

message ListSenMLMessagesRes {
    uint64           total    = 1;
    repeated Message messages = 2;
}

