name: build status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Go tests
      run: go test ./...

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Swagger UI action
      id: swagger-ui-action
      uses: Legion2/swagger-ui-action@v1
      with:
        dir: "./api/openapi"
        pattern: "*.yml"
        debug: "true"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: swagger-ui
        cname: mainfluxlabs.github.io/mainflux
